# Generated by Django 5.1.2 on 2024-11-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
